### PR TITLE
Survey answer

### PR DESCRIPTION
**Pull request by Binyamin-Brion**
- Added controller for answer and required components for survey
- Fixed errors in tests
- Removed unneeded imports

### CODE REVIEW

**Review by frankliu197 — APPROVED** [review]
looks good

**Review by aeiou80 — APPROVED** [review]
Pipeline passed, code's nice. Looks good!

**Comment by aeiou80** [comment]
I've already done the initial Heroku deployment so someone else can merge into master this time

https://dashboard.heroku.com/apps/mini-surveymonkey-4806

**Review by doodlehead — APPROVED** [review]
Looks good for first iteration. We can probably worry about validation later

**Pull request merged**
